#-------------------------------
# General Site Settings

menu:
#- {name: 'About', url: ''}
- {name: 'Research', url: 'publications.html'}
#- {name: 'Software', url: 'software.html'}
- {name: 'Long Bio', url: 'long_bio.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Theodoros Stouraitis is a robotics researcher that envisions a future where robots co-exist with humans and naturally augment
  humans capabilities.'
  rel-author: 'Theodoros Stouraitis'
  rel-publisher: 'Theodoros Stouraitis'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-113566398-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  ## About Me

  <img src="/assets/img/Theo_new.png" alt="Drawing" style="width: 25%;"/>
  <img src="/assets/img/concept.gif" align="right" alt="Drawing" style="padding:5px;border:medium solid grey; width: 40%;"/>

  <p class="lead" style="font-variant:small-caps">
      Human-Robot Collaboration and Assistance - Manipulation - Uncertainty - Optimal Control
      <br />
  </p>

  I envision a future where robots co-exist with humans and naturally augment
  humans capabilities. Having this in mind, I venture to develop the required theory towards
  demonstrating scenarios where a robot assists a human manipulate and co-manipulate objects.


  #### Areas of scientific interest: ####

  + Numerical Optimal Control---Trajectory Optimization

  + Hybrid Systems

  + Uncertainty-aware (robust) estimation, prediction, planning and control


  #### Appliaction domains: ####

  + Manipulation---non-prehensile, sequential, collaborative and impact-aware

  + Human-Robot physical collaboration and assistance


  #### Short Bio: ####

  I am Senior Scientist at the [Honda Research Institute Europe](https://www.honda-ri.de).
  Prior to that, I was a Visiting Scientist at the [IRG](https://interactive.mit.edu) at Massachusetts Institute of Technology (MIT), USA,
  where I was adviced by [Prof. Julie Shah](https://interactive.mit.edu/about/people/julie).
  I obtained my PhD in Robotics from the University of Edinburgh, UK,
  under the supervision of [Prof. Sethu Vijayakumar](http://homepages.inf.ed.ac.uk/svijayak/) at the
  [SLMC group](https://web.inf.ed.ac.uk/slmc) and [Dr. Michael Gienger](https://scholar.google.de/citations?user=oU2jyxMAAAAJ&hl=de) at
  the [Honda Research Institute Europe](https://www.honda-ri.de).
  My PhD studies were supported in full by the Honda Research Institute Europe fellowship as
  part of the [HRI-EU European Graduate Network](https://www.honda-ri.de/partnership-in-science/).
  Prior to my PhD studies, I completed a MSc in Artificial Intelligence
  at the University of Edinburgh, I worked as Research Assistant for
  three years at the [Robotics and Mechatronics Institute of DLR](https://www.dlr.de/rm/en/desktopdefault.aspx/tabid-8017)
  (German Aerospace Center) and I obtained a Diploma (BSc + MSc)
  in Computer Engineering and Informatics from the University
  of Patras, Greece.



#-------------------------------
# Research Section

research: >
  ## Research

  Please find below the full list of papers, that I have been involved with.
# You can find a short description and extra material of each paper by clicking on the title.


#-------------------------------
# Work Section

#projects:
#- {name: 'Hierarchical Planning of Dynamic Movements without Scheduled Contact Sequences', folder: 'hierarchical', file: 'projects/hierarchical.html'}
#- {name: 'Planning and Execution of Dynamic Whole-Body Locomotion for a Hydraulic Quadruped on Challenging Terrain', folder: 'decoupled', file: 'projects/decoupled.html'}
# In such a scenario, a robot agent can collaborate with a human,
# as naturally as two humans would do.
#  demonstrating Dyadic collaborative Manipulation (DcM) scenarios between a human and a robot,
# My scientific focus is on-line motion planning
# algorithms based on numerical optimal control theory and machine learning models that can
# be used to estimate and predict physical interactions with humans.
# Further, I am very keen on investigating representations that can enable robustness in
# optimal control methods, as well as the structural composition of optimal control methods with search-based planning
# methods.

#-------------------------------
# Software Section

#software: >
  ## Software


#-------------------------------
# Long Bio Section

long_bio: >

  ## Long Bio

  My first experience in robotics research was during my diploma thesis 2011 at the University of
  Patras, Greece, under the supervision of
  [Prof. Antony Tzes](https://nyuad.nyu.edu/en/academics/divisions/engineering/faculty/anthony-tzes.html).
  I explored probabilistic filtering based methods, specifically Particle Filters, towards adressing the SLAM problem
  for a mobile ground robot. Being fascinated from my first experience in the field, in January 2012
  I moved abroad and joined the Institute of Robotics and Mechatronics at the German Aerospace Center
  (DLR). At DLR, I primarily worked with [Dr. Máximo Roa](https://rmc.dlr.de/rm/de/staff/maximo.roa/)
  and numerous other great colleagues on grasp planning, grasp simulations, physics engines
  and software development. During this period I got familiar with many robotic areas, co-published
  a number of papers and actively participated in two European projects, namely
  [SMErobotics](http://www.smerobotics.org) and [EUROC](http://www.euroc-project.eu).
  Driven by my belief that learning is the key towards developing truly intelligent robots.
  In September 2015 I decided to enhance my education on Machine Learning and Intelligent Robotics,
  joining the MSc in Artificial Intelligence at the University of Edinburgh. My MSc thesis was on
  the interdisciplinary area of bio-robotics, under the supervision of
  [Prof. Barbara Webb](http://homepages.inf.ed.ac.uk/bwebb/). During my thesis I developed an
  onmi-directional robot with 360-degrees vision, that immitates the behaviour of fiddler crabs
  under predation. During my MSc I also had the luck to get to know
  [Prof. Sethu Vijayakumar](http://homepages.inf.ed.ac.uk/svijayak/),
  which led to my enrollment at the [Edinburgh Centre for Robotics (ECR)](https://www.edinburgh-robotics.org) in
  September 2016 as a PhD student. My PhD studies were supported in full by the Honda Research Institute Europe Fellowship as
  part of the [HRI-EU European Graduate Network](https://www.honda-ri.de/partnership-in-science/) and
  were conducted under [Prof. Sethu Vijayakumar's](http://homepages.inf.ed.ac.uk/svijayak/) and
  [Dr. Michael Gienger's](https://scholar.google.de/citations?user=oU2jyxMAAAAJ&hl=de) supervision.
  I completed my PhD studies in 2021 on the topic of Human-Robot Collaboration and
  continued working as Research Associate at the
  [SLMC group](https://web.inf.ed.ac.uk/slmc) at the University of Edinburgh.
  In 2022, I was a Visiting Scientist at the [IRG](https://interactive.mit.edu) at Massachusetts Institute of Technology (MIT), USA, for 3 months,
  where I was adviced by [Prof. Julie Shah](https://interactive.mit.edu/about/people/julie) and I investigate topics related to
  estimation and planning for Human-Robot assistive tasks. My visit at MIT was supported in part by a Postdoctoral Grant provided by
  the [Scottish Informatics and Computer Science Alliance (SICSA)](https://www.sicsa.ac.uk).
  I am now a Senior Scientist at the [Honda Research Institute Europe](https://www.honda-ri.de) working towards developing robots that assist humans in daily tasks.



#-------------------------------
# Contact Section

contact: >
  ## Contact

  If you'd like to know more about my research or would just like to discuss past or future projects,
  feel free to contact me [by email](mailto:stoutheo@gmail.com) or through [LinkedIn](https://www.linkedin.com/in/theodoros-stouraitis-59083045/).


social:
- {icon: 'github', link: 'https://github.com/stoutheo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/theodoros-stouraitis-59083045/'}
- {icon: 'scholar', link: 'https://scholar.google.co.uk/citations?user=dFv2yTQAAAAJ&hl=el'}
- {icon: 'twitter', link: 'https://twitter.com/t_stou'}
- {icon: 'envelope', link: 'mailto:stoutheo@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
